import { NextResponse } from "next/server";
import { createClient as createSupabase } from "@supabase/supabase-js";
import { checkPublicToken } from "@/lib/api/public-token";
import type { TradingBrief, TradingEdition } from "@/lib/trading/types";

export const dynamic = "force-dynamic";

function service() {
  return createSupabase(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);
}

function todayBRT(): string {
  return new Date().toLocaleDateString("en-CA", { timeZone: "America/Sao_Paulo" });
}

/**
 * GET /api/public/trading?date=YYYY-MM-DD&edition=morning|closing
 *
 * Auth: header X-API-Key (matched against WL_API_TOKENS env CSV).
 *
 * Returns the global trading brief generated by the service user
 * (TRADING_GLOBAL_USER_ID). If `edition` is omitted, returns both
 * morning and closing for the date.
 *
 * Response shape:
 *   { date: string, morning: TradingBrief | null, closing: TradingBrief | null }
 *
 * Used by whitelabel-v1 to surface the brief inside league screens.
 */
export async function GET(request: Request) {
  const tokenError = checkPublicToken(request);
  if (tokenError) return tokenError;

  const globalUserId = process.env.TRADING_GLOBAL_USER_ID;
  if (!globalUserId) {
    return NextResponse.json(
      { error: "TRADING_GLOBAL_USER_ID not configured" },
      { status: 503 },
    );
  }

  const { searchParams } = new URL(request.url);
  const date = searchParams.get("date") || todayBRT();
  const editionParam = searchParams.get("edition");
  const editions: TradingEdition[] =
    editionParam === "morning" || editionParam === "closing"
      ? [editionParam]
      : ["morning", "closing"];

  const svc = service();
  const { data, error } = await svc
    .from("trading_briefs")
    .select("*")
    .eq("user_id", globalUserId)
    .eq("date", date)
    .in("edition", editions);

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  const briefs = (data ?? []) as TradingBrief[];
  const morning = briefs.find((b) => b.edition === "morning") ?? null;
  const closing = briefs.find((b) => b.edition === "closing") ?? null;

  return NextResponse.json({ date, morning, closing });
}
